# POST http://localhost:8000/bands
# Content-Type: application/json

# {
# 	"name": "old  Band",
# 	"genre": "RoCK",
# 	"albums": [
# 		{"title": "First Album","release_date": "2000-01-01"}
# 	]
# }


##

GET http://localhost:8000/bands